name: GamingSystem-CI

on:
  push:
    branches:
      - main

env:
  ACR_NAME: gamingsystemacr.azurecr.io
  IMAGE_TAG: latest

jobs:

  build-and-push-images:

    runs-on: ubuntu-latest

    steps:

    # Checkout Repository
    - name: Checkout Repository
      uses: actions/checkout@v4

    # Setup .NET 8
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Restore Backend Services
    - name: Restore Backend Services
      run: |
        dotnet restore backend/MicroservicesSolution/GameService.API/GameService.API.csproj
        dotnet restore backend/MicroservicesSolution/PlayerService.API/PlayerService.API.csproj
        dotnet restore backend/MicroservicesSolution/RankingService.API/RankingService.API.csproj
        dotnet restore backend/MicroservicesSolution/ScoreService.API/ScoreService.API.csproj

    # Build Backend Services
    - name: Build Backend Services
      run: |
        dotnet build backend/MicroservicesSolution/GameService.API/GameService.API.csproj --configuration Release
        dotnet build backend/MicroservicesSolution/PlayerService.API/PlayerService.API.csproj --configuration Release
        dotnet build backend/MicroservicesSolution/RankingService.API/RankingService.API.csproj --configuration Release
        dotnet build backend/MicroservicesSolution/ScoreService.API/ScoreService.API.csproj --configuration Release

    # Setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    # Install Angular Dependencies
    - name: Install Angular Dependencies
      run: |
        cd gaming-ui/gaming-ui
        npm install

    # Build Angular App
    - name: Build Angular App
      run: |
        cd gaming-ui/gaming-ui
        npm run build

    # Login to Azure Container Registry
    - name: Login to Azure Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    # Build GameService Docker Image
    - name: Build GameService Docker Image
      run: |
        docker build \
        -t $ACR_NAME/gaming-system-gameservice:$IMAGE_TAG \
        backend/MicroservicesSolution/GameService.API

    # Push GameService Docker Image
    - name: Push GameService Docker Image
      run: |
        docker push \
        $ACR_NAME/gaming-system-gameservice:$IMAGE_TAG

    # Build PlayerService Docker Image
    - name: Build PlayerService Docker Image
      run: |
        docker build \
        -t $ACR_NAME/gaming-system-playerservice:$IMAGE_TAG \
        backend/MicroservicesSolution/PlayerService.API

    # Push PlayerService Docker Image
    - name: Push PlayerService Docker Image
      run: |
        docker push \
        $ACR_NAME/gaming-system-playerservice:$IMAGE_TAG

    # Build RankingService Docker Image
    - name: Build RankingService Docker Image
      run: |
        docker build \
        -t $ACR_NAME/gaming-system-rankingservice:$IMAGE_TAG \
        backend/MicroservicesSolution/RankingService.API

    # Push RankingService Docker Image
    - name: Push RankingService Docker Image
      run: |
        docker push \
        $ACR_NAME/gaming-system-rankingservice:$IMAGE_TAG

    # Build ScoreService Docker Image
    - name: Build ScoreService Docker Image
      run: |
        docker build \
        -t $ACR_NAME/gaming-system-scoreservice:$IMAGE_TAG \
        backend/MicroservicesSolution/ScoreService.API

    # Push ScoreService Docker Image
    - name: Push ScoreService Docker Image
      run: |
        docker push \
        $ACR_NAME/gaming-system-scoreservice:$IMAGE_TAG

    # Build Angular UI Docker Image
    - name: Build Angular UI Docker Image
      run: |
        docker build \
        -t $ACR_NAME/gaming-system-ui:$IMAGE_TAG \
        gaming-ui/gaming-ui

    # Push Angular UI Docker Image
    - name: Push Angular UI Docker Image
      run: |
        docker push \
        $ACR_NAME/gaming-system-ui:$IMAGE_TAG